# Custom values for the event-exporter chart
# These will override the default values from the base chart

# Service account configuration for AWS Secrets Manager access
# This ServiceAccount will be annotated with the IAM role for fetching secrets
serviceAccount:
  name: event-exporter
  # The role ARN should match the one created by CDKTF app-iam module
  # The format is: ${cluster-name}-${namespace}-${app-name}-role
  roleArn: "arn:aws:iam::961341519925:role/layerx-eks-monitoring-event-exporter-role" # Will be replaced with the actual role ARN from CDKTF outputs
  # Example: "arn:aws:iam::123456789012:role/layerx-eks-monitoring-event-exporter-role"

# External Secrets configuration
# This tells the External Secrets Operator which AWS secret to fetch
externalSecrets:
  enabled: true
  region: "eu-central-1"  # Region where your secrets are stored
  secretName: "home-assignments/layerx"  # Name of your secret in AWS Secrets Manager
  # Note: The AWS secret should contain a key "slack-webhook-url" with the webhook URL

kubernetes-event-exporter:
  # All values under this key will be passed to the base chart
  config:
    logLevel: debug  # Set to debug for more detailed logs
    logFormat: json
    receivers:
      - name: default
        stdout: {}
      - name: slack-webhook
        webhook:
          endpoint: "${SLACK_WEBHOOK_URL}"
          headers:
            Content-Type: "application/json"
            User-Agent: "kubernetes-event-exporter"
          layout:  # Customize the JSON payload sent to Slack
            text: "🔔 *Kubernetes Event Alert*\n*Type:* {{ .Type }}\n*Reason:* {{ .Reason }}\n*Namespace:* {{ .InvolvedObject.Namespace }}\n*Object:* {{ .InvolvedObject.Kind }}/{{ .InvolvedObject.Name }}"
    route:
      routes:
        - match:
            - receiver: default
        - drop:
            - type: "Normal"
          match:
            - receiver: slack-webhook

  # Pod configuration
  extraEnvVars:
    - name: SLACK_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: slack-webhook  # Must match the target.name in ExternalSecret
          key: url             # Must match the secretKey in ExternalSecret
