{{- if .Values.externalSecrets.enabled }}
# External Secret definition for fetching the Slack webhook
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: slack-webhook-url
---
# SecretStore specifically for this namespace and service account
# This leverages the global External Secrets Operator AWS provider configuration
# but with this app-specific ServiceAccount for authentication
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: {{ .Release.Namespace }}
{{- end }}
